Module 3
twelwet/ps-nodejs pull request #1
Opened 2024-12-06 14:25 UTC by twelwet

2024-12-26 11:03 UTC, alex13slem requested changes

2024-12-26 11:03 UTC, alex13slem commented on 3-calc-events/actions/divide.js
> +const divide = (a, b) => console.log(`${a} / ${b} = ${a / b}`);
Для операции деления (divide) необходимо добавить проверку, чтобы избежать деления на 0

2024-12-26 11:03 UTC, alex13slem commented on 3-calc/index.js
> +const actionName = actions.map((it) => it.name).find((it) => it === argv[4]) ? argv[4] : DEFAULT_ACTION_NAME;
Если пользователь вводит неверное действие, можно выводить сообщение с доступными действиями

2024-12-26 11:03 UTC, alex13slem commented on 3-calc/index.js
> +fn(firstNum, secondNum);
Лучше сделать функции "чистыми", то есть одна функция выполняет лишь одну операцию. Если функция производит расчёт - то она производит только расчёт, без дополнительного действия (вывода результата в консоль). А результат в консоль выводить дальше в процессе, либо в дальнейшем не выводить, а производить с ним какие-то иные операции.

2024-12-26 11:03 UTC, alex13slem commented on 4-timer/util/util.js
> +		hour >= MAX_HOUR ? DEFAULT_HOUR : hour,
Убедитесь, что вводимые аргументы корректны (являются числами и в пределах допустимого диапазона).
Добавьте обработку сценария, когда пользователи вводят значения за пределами логики таймера.
Желательно не тихо подменять некорректные данные - а сообщать о некорректных данных пользователю.

2024-12-26 11:03 UTC, alex13slem commented on 5-threads/index.js
> +const availableThreads = os.availableParallelism() || DEFAULT_THREADS;
Проверка доступности os.availableParallelism(): Если проект должен поддерживать версии Node.js ниже 20, добавьте условие для обратной совместимости. Например:
```js
const availableThreads = os.availableParallelism ? os.availableParallelism() : DEFAULT_THREADS
```

2024-12-29 08:46 UTC, twelwet commented on 3-calc-events/actions/divide.js
> +const divide = (a, b) => console.log(`${a} / ${b} = ${a / b}`);
Добавил

2024-12-29 08:47 UTC, twelwet commented on 3-calc/index.js
> +const actionName = actions.map((it) => it.name).find((it) => it === argv[4]) ? argv[4] : DEFAULT_ACTION_NAME;
Добавлена валидация вводимых данных

2024-12-29 08:48 UTC, twelwet commented on 3-calc/index.js
> +fn(firstNum, secondNum);
Сделал функции "чистыми"

2024-12-29 08:48 UTC, twelwet commented on 4-timer/util/util.js
> +		hour >= MAX_HOUR ? DEFAULT_HOUR : hour,
Добавлена валидация вводимых данных

2024-12-29 08:48 UTC, twelwet commented on 5-threads/index.js
> +const availableThreads = os.availableParallelism() || DEFAULT_THREADS;
Добавил

2025-01-03 06:38 UTC, alex13slem requested changes

2025-01-03 06:38 UTC, alex13slem commented on 3-calc/actions/divide.js
> +const divide = (a, b) => b === 0 ? undefined : a / b;
Тут бы выбрасывать ошибку, а не возвращать undefined

2025-01-03 06:38 UTC, alex13slem commented on 3-calc/actions/divide.js
> +const divide = (a, b) => b === 0 ? undefined : a / b;
В целом выбрасывание ошибок там, где они могут потенциально появиться и обработка ошибок с помощью try/catch значительно бы упростило код.

2025-02-20 09:16 UTC, EsilSemitone commented on 4-timer/util/util.js
> +const Minute = { MIN: 0, MAX: 59 };
Лучше прописать капсом и вынести отдельно, а еще можно упростить и написать подобным образом
const HOUR = (arg) => { 
    return {
        arg, 
        minValue: 0, 
        maxValue: 23 , 
        message: 'Количество часов'
    }
};

В таком случае в функции validate data будет выглядеть как-то так
const data = [HOUR(argv2), MINUTE(argv2)...]
Или можно сделать HOUR, MINUTE и тд классами

2025-02-20 09:16 UTC, EsilSemitone commented on 4-timer/util/util.js
> +		switch (argv) {
лучше переписать без switch выглядит довольно громозко и трудночитаемо

2025-02-20 09:16 UTC, EsilSemitone commented on 5-threads/index.js
> +const DIVIDER = 3;
так же лучше вынести отдельно напр. в файл constants.js

2025-02-20 09:16 UTC, EsilSemitone commented on 8-weather-extended/services/api.service.js
> +			return '🌤️';
по возможности лучше избегать switch case, в случаях как здесь лучше переписать на map или обьект

2025-02-20 09:16 UTC, EsilSemitone commented on 8-weather-extended/weather.js
> +	if (argv.h) {
лучше переписать эту часть на map подобным образом
const commandMap = new Map([
    ["h", command1],
    ["t", command2],
])

for (const [arg, value] of Object.entries(argv)) {
    const command = commandMap.get(arg)
    if (command) {
        return command(value)
    }
}

2025-02-20 09:16 UTC, EsilSemitone commented on README.md
> +2. Сделать калькулятор с использованием модулей.
Привет! Каждое задание необходимо отправлять в отдельном pull request

2025-02-21 09:11 UTC, twelwet commented on 4-timer/util/util.js
> +const Minute = { MIN: 0, MAX: 59 };
+

2025-02-21 09:36 UTC, twelwet commented on 4-timer/util/util.js
> +		switch (argv) {
Поправил

2025-02-21 09:41 UTC, twelwet commented on 5-threads/index.js
> +const DIVIDER = 3;
Поправил

2025-02-21 10:10 UTC, twelwet commented on 8-weather-extended/services/api.service.js
> +			return '🌤️';
Поправил

2025-02-21 14:52 UTC, twelwet commented on 8-weather-extended/weather.js
> +	if (argv.h) {
Поправил

2025-02-21 14:54 UTC, twelwet commented on README.md
> +2. Сделать калькулятор с использованием модулей.
Привет!
Со следующего задания начну отправлять каждое новое - в отдельном pull request.

Если больше замечаний нет, можешь смерджить все изменения в ветку 'main'?

2025-02-21 15:04 UTC, EsilSemitone approved these changes

2025-02-21 15:05 UTC, merged